"""initial survey schema

Revision ID: dfff7ad1cdc6
Revises: 
Create Date: 2026-07-14 19:05:27.990151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfff7ad1cdc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('font_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('relative_path', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('axes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    sa.UniqueConstraint('version')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('font_asset_id', sa.Integer(), nullable=False),
    sa.Column('display_defaults', sa.JSON(), nullable=False),
    sa.Column('body_defaults', sa.JSON(), nullable=False),
    sa.Column('display_sample', sa.Text(), nullable=False),
    sa.Column('body_sample', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['font_asset_id'], ['font_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('survey_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('experiment_snapshot', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('viewport', sa.JSON(), nullable=False),
    sa.Column('browser_family', sa.String(length=40), nullable=True),
    sa.Column('variable_font_supported', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_code')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('likes', sa.Text(), nullable=False),
    sa.Column('dislikes', sa.Text(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('feelings', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('role_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('initial', sa.JSON(), nullable=False),
    sa.Column('final', sa.JSON(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('sample_edited', sa.Boolean(), nullable=False),
    sa.Column('legibility_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('control', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuning_events')
    op.drop_table('role_configs')
    op.drop_table('feedback')
    op.drop_table('survey_sessions')
    op.drop_table('experiments')
    op.drop_table('font_assets')
    # ### end Alembic commands ###
